name: LXC Setup
description: Setup an LXC Container on GitHub Actions
author: Lars Kiesow
inputs:
  dist:
    required: true
    description: LXC distribution template
    default: centos
  release:
    required: true
    description: Distribution release
    default: 9-Stream
  name:
    required: true
    description: Container name
    default: test
  configure-etc-hosts:
    required: true
    description: If to configure the container name and IP address in /etc/hosts
    default: true
  configure-ssh:
    required: true
    description: If to configure an SSH key
    default: true
  lxc-init:
    required: false
    description: >
      Commands to use for setting up the container (e.g. configure SSH).
      Setting this will overwrite in-container openssh-server installation
      for supported distributions.
outputs:
  ip:
    description: IP address of the container that was set up.
runs:
  using: node16
  main: dist/index.js
